const {UiColor, FontFamily, TextSize, TextColor} = require('../../theme');
import {StyleSheet} from 'react-native';
import {w, h, width, height} from '../../utils/Dimensions';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: UiColor.WHITE,
  },
  searchContainer: {
    marginVertical: 10,
    height: h(5.5),
    width: '75%',
    marginLeft: 10,
  },
  search: {
    backgroundColor: UiColor.GRAY_BACKGROUND,
    height: h(6),
  },
  filter: {
    height: h(6),
    width: w(6),
    tintColor: UiColor.DARK_GRAY,
    backgroundColor: 'transparent',
    alignSelf: 'center',
  },
  filterContainer: {
    marginVertical: 10,
    height: h(6),
    width: w(14),
    backgroundColor: UiColor.GRAY_BACKGROUND,
    borderRadius: 5,
    elevation: 2,
  },
  image: {
    height: 120,
    width: 330,
    alignSelf: 'flex-start',
    borderRadius: 10,
    marginHorizontal: 10,
    marginVertical: 10,
  },
  circleImage: {
    height: 60,
    width: 60,
    borderRadius: 80,
    elevation: 5,
    alignSelf: 'center',
  },
  bottomLine: {
    borderWidth: 0.5,
    height: 1,
    width: 330,
    marginHorizontal: 10,
    marginVertical: 5,
    borderColor: UiColor.GRAYLINE,
  },
  circleImageTextContainer: {
    flexDirection: 'row',
    width: 100,
  },
  circleImageText: {
    paddingLeft: 25,
    color: TextColor.GRAY,
    fontSize: TextSize.h9,
    fontFamily: FontFamily.REGULAR,
  },
  productContainer: {
    backgroundColor: UiColor.GRAY_BACKGROUND,
    flex: 2,
  },
  seeAllContainer: {
    flexDirection: 'row',
    borderTopWidth: 0.5,
    paddingHorizontal: 10,
    borderColor: UiColor.GRAY,
    justifyContent: 'space-between',
    backgroundColor: UiColor.GRAY,
  },
  productsHeadingText: {
    paddingLeft: 10,
    fontSize: TextSize.h6,
    fontFamily: FontFamily.SEMIBOLD,
    color: TextColor.DARK_GRAY,
  },
  seeAllText: {
    paddingRight: 10,
    fontSize: TextSize.h8,
    fontFamily: FontFamily.SEMIBOLD,
    color: TextColor.ORANGE,
  },
  TopProductcardContainer: {
    elevation: 5,
    borderRadius: 10,
    marginHorizontal: 5,
    marginBottom: 20,
    width: w(33),
    paddingTop: 5,
  },
  TopProductImage: {
    height: 60,
    width: 45,
    marginTop: 20,
    marginLeft: 35,
  },
  topProductPlaceholder: {
    resizeMode: 'contain',
    height: 10,
    tintColor: UiColor.GRAY,
  },
  topPlaceholder: {
    resizeMode: 'contain',
    height: 60,
    tintColor: UiColor.GRAY,
  },

  circlePlaceholder: {
    tintColor: UiColor.GRAY,
    resizeMode: 'contain',
    height: 10,
  },
  amount: {
    fontSize: TextSize.h8,
    fontFamily: FontFamily.SEMIBOLD,
    paddingLeft: 10,
    paddingTop: 5,
  },
  productTitle: {
    fontSize: 8,
    color: TextColor.GRAY,
    paddingHorizontal: 10,
    fontFamily: FontFamily.REGULAR,
  },
  cartbutton: {
    width: w(30.7),
    height: h(4),
    marginTop: 10,
    marginLeft: 4,
    borderBottomRightRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: UiColor.ORANGE,
  },
  cartText: {
    color: UiColor.WHITE,
    textAlign: 'center',
    paddingTop: 3,
    fontFamily: FontFamily.BOLD,
    fontSize: TextSize.h8,
  },
  specialOfferPlaceholder: {
    resizeMode: 'center',
    height: 5,
    tintColor: UiColor.GRAY,
  },

  SpecialOfferscardContainer: {
    backgroundColor: UiColor.WHITE,
    flexDirection: 'column',
    elevation: 3,
    borderRadius: 10,
    marginHorizontal: 10,
  },
  Offersimage: {
    height: 100,
    width: 100,
    borderRadius: 40,
    marginHorizontal: 10,
  },
  title: {
    alignSelf: 'flex-start',
    paddingTop: 15,
    fontSize: TextSize.h8,
    paddingLeft: 10,
    fontFamily: FontFamily.BOLD,
    color: TextColor.GREEN,
  },
  category: {
    alignSelf: 'flex-start',
    paddingLeft: 7,
    fontSize: TextSize.h8,
    fontFamily: FontFamily.BOLD,
    color: TextColor.GRAY,
  },
  subcategories: {
    alignSelf: 'flex-start',
    paddingLeft: 10,
    fontSize: TextSize.h9,
    fontFamily: FontFamily.REGULAR,
    color: TextColor.GRAY,
  },
  VegetablecardContainer: {
    backgroundColor: UiColor.WHITE,
    flexDirection: 'column',
    elevation: 3,
    borderRadius: 4,
    marginHorizontal: 10,
    paddingVertical: 10,
  },
  Vegetableimage: {
    height: 60,
    width: 100,
    borderRadius: 40,
    marginHorizontal: 10,
  },
  Vegetabletitle: {
    fontSize: TextSize.h7,
    fontFamily: FontFamily.REGULAR,
    color: TextColor.GRAY,
    paddingLeft: 10,
  },
  bracketTitle: {
    fontSize: 8,
    paddingTop: 4,
    color: TextColor.GRAY,
  },
  slideDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginHorizontal: 0,
    padding: 0,
    margin: 0,
  },
});
